"""Report generation for trade show trend analysis.

Produces formatted reports in Markdown, JSON, or HTML.
"""

import json
import logging
from datetime import datetime
from pathlib import Path

from .analyzer import AnalysisReport, TrendSummary

logger = logging.getLogger(__name__)


class ReportGenerator:
    """Generates formatted analysis reports."""

    def __init__(self, output_dir: Path):
        self.output_dir = output_dir
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def generate(self, report: AnalysisReport, fmt: str = "markdown") -> Path:
        """Generate a report file and return its path."""
        timestamp = datetime.utcnow().strftime("%Y%m%d_%H%M%S")

        if fmt == "markdown":
            return self._generate_markdown(report, timestamp)
        elif fmt == "json":
            return self._generate_json(report, timestamp)
        elif fmt == "html":
            return self._generate_html(report, timestamp)
        else:
            raise ValueError(f"Unknown format: {fmt}")

    def _generate_markdown(self, report: AnalysisReport, timestamp: str) -> Path:
        """Generate a Markdown report."""
        path = self.output_dir / f"tradeshow_trends_{timestamp}.md"
        lines = []

        lines.append("# Trade Show Trend Analysis Report")
        lines.append(f"\n**Generated:** {report.timestamp}")
        lines.append(f"**Signals Analyzed:** {report.total_signals_analyzed}")
        lines.append(f"**Events Covered:** {report.total_events_covered}")
        lines.append("")

        # --- Global Top Trends ---
        lines.append("## Global Top Trends")
        lines.append("")
        for i, trend in enumerate(report.global_trends, 1):
            signal_emoji = {"emerging": "[NEW]", "growing": "[UP]", "mature": "[STABLE]", "declining": "[DOWN]"}
            marker = signal_emoji.get(trend.signal_type, "")
            lines.append(f"### {i}. {trend.title} {marker}")
            lines.append(f"**Score:** {trend.score} | **Type:** {trend.signal_type} "
                         f"| **Confidence:** {trend.avg_confidence:.0%}")
            lines.append(f"**Mentions:** {trend.total_mentions} across "
                         f"{len(trend.source_events)} events")
            lines.append(f"**Industries:** {', '.join(trend.industries)}")
            lines.append(f"**Regions:** {', '.join(trend.regions)}")
            if trend.is_cross_industry:
                lines.append("*Cross-industry trend*")
            if trend.is_global:
                lines.append("*Global reach*")
            lines.append(f"\n{trend.description}")
            if trend.all_keywords:
                lines.append(f"\n**Keywords:** {', '.join(trend.all_keywords[:8])}")
            lines.append("")

        # --- Cross-Industry Themes ---
        if report.cross_industry_themes:
            lines.append("## Cross-Industry Convergence Themes")
            lines.append("")
            for theme in report.cross_industry_themes:
                lines.append(f"- **{theme.title}**: Spans {', '.join(theme.industries[:4])}. "
                             f"Score: {theme.score}")
            lines.append("")

        # --- Industry Insights ---
        lines.append("## Industry Insights")
        lines.append("")
        for insight in report.industry_insights:
            lines.append(f"### {insight.industry}")
            lines.append(f"**Direction:** {insight.trend_direction} | "
                         f"**Key Theme:** {insight.key_theme}")
            lines.append(f"**Active Shows:** {', '.join(insight.active_shows[:5])}")
            if insight.top_trends:
                lines.append("\nTop trends:")
                for t in insight.top_trends[:3]:
                    lines.append(f"  - {t.title} (score: {t.score})")
            lines.append("")

        # --- Regional Insights ---
        lines.append("## Regional Insights")
        lines.append("")
        for insight in report.regional_insights:
            lines.append(f"### {insight.region}")
            lines.append(f"**Market Sentiment:** {insight.market_sentiment}")
            lines.append(f"**Dominant Industries:** {', '.join(insight.dominant_industries)}")
            if insight.top_trends:
                lines.append("\nTop trends:")
                for t in insight.top_trends[:3]:
                    lines.append(f"  - {t.title} (score: {t.score})")
            lines.append("")

        # --- Emerging Opportunities ---
        if report.emerging_opportunities:
            lines.append("## Emerging Opportunities")
            lines.append("")
            for opp in report.emerging_opportunities:
                lines.append(f"- {opp}")
            lines.append("")

        lines.append("---")
        lines.append("*Report generated by AutoResearch Trade Show Trend Analysis Agent*")

        path.write_text("\n".join(lines))
        logger.info(f"Markdown report saved to {path}")
        return path

    def _generate_json(self, report: AnalysisReport, timestamp: str) -> Path:
        """Generate a JSON report."""
        path = self.output_dir / f"tradeshow_trends_{timestamp}.json"

        def trend_to_dict(t: TrendSummary) -> dict:
            return {
                "title": t.title,
                "description": t.description,
                "score": t.score,
                "signal_type": t.signal_type,
                "industries": t.industries,
                "regions": t.regions,
                "source_events": t.source_events,
                "total_mentions": t.total_mentions,
                "avg_confidence": t.avg_confidence,
                "keywords": t.all_keywords,
                "is_cross_industry": t.is_cross_industry,
                "is_global": t.is_global,
            }

        data = {
            "timestamp": report.timestamp,
            "summary": {
                "total_signals": report.total_signals_analyzed,
                "total_events": report.total_events_covered,
            },
            "global_trends": [trend_to_dict(t) for t in report.global_trends],
            "cross_industry_themes": [trend_to_dict(t) for t in report.cross_industry_themes],
            "industry_insights": [
                {
                    "industry": i.industry,
                    "trend_direction": i.trend_direction,
                    "key_theme": i.key_theme,
                    "active_shows": i.active_shows,
                    "top_trends": [trend_to_dict(t) for t in i.top_trends],
                }
                for i in report.industry_insights
            ],
            "regional_insights": [
                {
                    "region": r.region,
                    "market_sentiment": r.market_sentiment,
                    "dominant_industries": r.dominant_industries,
                    "top_trends": [trend_to_dict(t) for t in r.top_trends],
                }
                for r in report.regional_insights
            ],
            "emerging_opportunities": report.emerging_opportunities,
        }

        path.write_text(json.dumps(data, indent=2))
        logger.info(f"JSON report saved to {path}")
        return path

    def _generate_html(self, report: AnalysisReport, timestamp: str) -> Path:
        """Generate an HTML report."""
        path = self.output_dir / f"tradeshow_trends_{timestamp}.html"

        # Generate markdown first, then wrap in HTML
        md_content = []
        md_content.append(f"<h1>Trade Show Trend Analysis Report</h1>")
        md_content.append(f"<p><strong>Generated:</strong> {report.timestamp} | "
                          f"<strong>Signals:</strong> {report.total_signals_analyzed} | "
                          f"<strong>Events:</strong> {report.total_events_covered}</p>")

        md_content.append("<h2>Global Top Trends</h2>")
        md_content.append("<table border='1' cellpadding='8' cellspacing='0'>")
        md_content.append("<tr><th>#</th><th>Trend</th><th>Score</th><th>Type</th>"
                          "<th>Industries</th><th>Regions</th><th>Mentions</th></tr>")
        for i, t in enumerate(report.global_trends, 1):
            md_content.append(
                f"<tr><td>{i}</td><td><strong>{t.title}</strong></td>"
                f"<td>{t.score}</td><td>{t.signal_type}</td>"
                f"<td>{', '.join(t.industries[:3])}</td>"
                f"<td>{', '.join(t.regions[:3])}</td>"
                f"<td>{t.total_mentions}</td></tr>"
            )
        md_content.append("</table>")

        if report.emerging_opportunities:
            md_content.append("<h2>Emerging Opportunities</h2><ul>")
            for opp in report.emerging_opportunities:
                md_content.append(f"<li>{opp}</li>")
            md_content.append("</ul>")

        html = f"""<!DOCTYPE html>
<html>
<head>
<title>Trade Show Trends - {timestamp}</title>
<style>
body {{ font-family: Arial, sans-serif; max-width: 1200px; margin: 0 auto; padding: 20px; }}
table {{ border-collapse: collapse; width: 100%; margin: 20px 0; }}
th {{ background-color: #2c3e50; color: white; }}
td, th {{ padding: 10px; text-align: left; }}
tr:nth-child(even) {{ background-color: #f2f2f2; }}
h1 {{ color: #2c3e50; }}
h2 {{ color: #34495e; border-bottom: 2px solid #3498db; padding-bottom: 5px; }}
</style>
</head>
<body>
{"".join(md_content)}
<hr>
<p><em>Report generated by AutoResearch Trade Show Trend Analysis Agent</em></p>
</body>
</html>"""

        path.write_text(html)
        logger.info(f"HTML report saved to {path}")
        return path


def print_report_summary(report: AnalysisReport):
    """Print a concise summary to stdout."""
    print("\n" + "=" * 70)
    print("  TRADE SHOW TREND ANALYSIS - SUMMARY")
    print("=" * 70)
    print(f"  Timestamp: {report.timestamp}")
    print(f"  Signals Analyzed: {report.total_signals_analyzed}")
    print(f"  Events Covered: {report.total_events_covered}")
    print("-" * 70)

    print("\n  TOP GLOBAL TRENDS:")
    for i, t in enumerate(report.global_trends[:5], 1):
        print(f"    {i}. {t.title} (score: {t.score}, type: {t.signal_type})")
        print(f"       Industries: {', '.join(t.industries[:3])}")
        print(f"       Regions: {', '.join(t.regions[:3])}")

    if report.cross_industry_themes:
        print("\n  CROSS-INDUSTRY THEMES:")
        for t in report.cross_industry_themes[:3]:
            print(f"    - {t.title}: {', '.join(t.industries[:3])}")

    if report.emerging_opportunities:
        print("\n  EMERGING OPPORTUNITIES:")
        for opp in report.emerging_opportunities[:3]:
            print(f"    - {opp}")

    print("\n" + "=" * 70)
