"""
ReportGenerator — the output and positioning engine for trade show intelligence.

Autoresearch parallel
---------------------
This agent is analogous to the "eval + report" stage of an ML pipeline.  Its
"model" is the set of templates, density settings, and persuasion frameworks
it uses to transform raw trend data into human-consumable reports.  The
``run_experiment`` loop modifies these parameters — template structure,
trend limits, insight density, persuasion framing — and keeps changes only
when a proxy quality metric improves.

Where SignalCollector optimizes *what* goes in and TrendAnalyzer optimizes
*how* data is scored, ReportGenerator optimizes *how insights are presented*.

Modifiable parameters (the knobs ``run_experiment`` turns):
    brief_template        — str template for trend briefs
    packet_template       — str template for prospect packets
    max_trends_per_report — int cap on trends per output
    insight_density       — str ("high", "medium", "low")
    persuasion_framework  — str ("urgency", "opportunity", "competitive")
"""

from __future__ import annotations

import copy
import json
import os
import pathlib
import random
from datetime import datetime
from typing import Optional

DATA_DIR = pathlib.Path(__file__).parent.parent / "data"

# ── Default templates ───────────────────────────────────────────────────────

_DEFAULT_BRIEF_TEMPLATE = """\
# {title}

*{trend_count} key trends identified | Generated {date}*

{trend_sections}

---
*Generated by TradeShowTrendAgent — autoresearch pipeline*
"""

_DEFAULT_PACKET_TEMPLATE = """\
# Intelligence Packet: {company_name}

*Industry: {industry} | Generated {date}*

## Executive Summary

Based on analysis of {relevant_count} trends relevant to {industry}, \
here are the key insights for {company_name}'s trade show strategy:

{trend_sections}

## Recommended Next Steps

1. Audit current exhibit strategy against these {trend_count} trends
2. Identify which trends align with your product roadmap
3. Evaluate competitor exhibit strategies at upcoming shows
4. Develop a differentiated booth concept that positions {company_name} as a leader

---
*Generated by TradeShowTrendAgent — autoresearch pipeline*
"""


class ReportGenerator:
    """Generates actionable intelligence reports from trend data.

    This agent owns the *output* layer.  It turns ranked trends from
    ``TrendAnalyzer`` into markdown reports targeted at different audiences:
    sales reps (trend briefs), prospects (intelligence packets), exhibit
    designers (design reports), and field teams (talking points).
    """

    def __init__(self, config: Optional[dict] = None):
        config = config or {}
        self.brief_template: str = config.get(
            "brief_template", _DEFAULT_BRIEF_TEMPLATE
        )
        self.packet_template: str = config.get(
            "packet_template", _DEFAULT_PACKET_TEMPLATE
        )
        self.max_trends_per_report: int = config.get(
            "max_trends_per_report", 5
        )
        self.insight_density: str = config.get("insight_density", "high")
        self.persuasion_framework: str = config.get(
            "persuasion_framework", "urgency"
        )

        # Internal tracking
        self._experiment_log: list[dict] = []

    # ── Public API ──────────────────────────────────────────────────────────

    def generate_trend_brief(
        self, trends: list[dict], industry: Optional[str] = None
    ) -> str:
        """Generate an Industry Trend Brief — the 3-minute read for sales reps.

        Parameters
        ----------
        trends : list[dict]
            Ranked trend dicts from ``TrendAnalyzer.analyze``.
        industry : str, optional
            Filter to trends touching this industry.

        Returns
        -------
        str
            Markdown-formatted trend brief.
        """
        if industry:
            trends = [
                t for t in trends if industry in t.get("industries", [])
            ]

        top = trends[: self.max_trends_per_report]
        title = (
            f"Trade Show Trend Brief: {industry}"
            if industry
            else "Global Trade Show Trend Brief"
        )

        sections: list[str] = []
        for t in top:
            section = self._format_trend_section(t)
            sections.append(section)

        return self.brief_template.format(
            title=title,
            trend_count=len(top),
            date=datetime.utcnow().strftime("%Y-%m-%d"),
            trend_sections="\n\n".join(sections),
        )

    def generate_prospect_packet(
        self, trends: list[dict], company_name: str, industry: str
    ) -> str:
        """Generate a Prospect-Specific Intelligence Packet.

        Parameters
        ----------
        trends : list[dict]
            Ranked trend dicts.
        company_name : str
            Target company for the packet.
        industry : str
            The prospect's primary industry.

        Returns
        -------
        str
            Markdown-formatted prospect packet.
        """
        relevant = [
            t for t in trends if industry in t.get("industries", [])
        ]
        top = relevant[: self.max_trends_per_report]

        sections: list[str] = []
        for t in top:
            section = self._format_trend_section(t)
            # Add persuasion callout
            callout = self._persuasion_callout(t, company_name)
            if callout:
                section += f"\n\n{callout}"
            sections.append(section)

        return self.packet_template.format(
            company_name=company_name,
            industry=industry,
            date=datetime.utcnow().strftime("%Y-%m-%d"),
            relevant_count=len(relevant),
            trend_count=len(top),
            trend_sections="\n\n".join(sections),
        )

    def generate_design_report(self, trends: list[dict]) -> str:
        """Generate a Design Trend Report for exhibit designers.

        Parameters
        ----------
        trends : list[dict]
            Ranked trend dicts.

        Returns
        -------
        str
            Markdown-formatted design report.
        """
        top = trends[: self.max_trends_per_report]

        lines = [
            "# Exhibit Design Trend Report",
            "",
            "## Design Implications from Current Trade Show Trends",
            "",
        ]

        for t in top:
            name = t.get("name", "Unknown")
            lifecycle = t.get("lifecycle", "emerging")
            score = t.get("composite_score", 0)
            lines.append(f"### {name}")
            lines.append(
                f"*{lifecycle.capitalize()} — Score: {score:.1f}*"
            )
            lines.append("")

            implications = t.get("design_implications", "")
            if implications:
                lines.append(f"**Design Direction:** {implications}")
            else:
                lines.append(
                    f"**Design Direction:** Exhibits featuring {name} "
                    f"should emphasize interactive demonstrations over "
                    f"static displays. Consider integrating live data feeds, "
                    f"hands-on stations, and workflow simulations that let "
                    f"attendees experience the technology."
                )
            lines.append("")

            keywords = t.get("keywords", [])
            if keywords and self.insight_density in ("high", "medium"):
                lines.append(
                    f"**Design keywords:** {', '.join(keywords)}"
                )
                lines.append("")

        lines.extend([
            "## General Design Trends",
            "",
            "- **Open engagement zones** outperforming guided-flow layouts",
            "- **Sustainable materials** driving 23% higher dwell time",
            "- **Interactive workflow simulations** replacing product showcases",
            "- **AI-powered personalization** for attendee experience",
            "- **Ambient technology** (LED-free lighting, spatial audio) "
            "replacing overt tech displays",
            "",
            "---",
            "*Generated by TradeShowTrendAgent — autoresearch pipeline*",
        ])
        return "\n".join(lines)

    def generate_talking_points(
        self, trends: list[dict], industry: str, show_name: str
    ) -> list[str]:
        """Generate conversation starters for sales reps at a specific show.

        Parameters
        ----------
        trends : list[dict]
            Ranked trend dicts.
        industry : str
            Target industry for the conversation.
        show_name : str
            Name of the upcoming trade show.

        Returns
        -------
        list[str]
            Talking point strings ready for use by field sales.
        """
        relevant = [
            t for t in trends if industry in t.get("industries", [])
        ]
        points: list[str] = []

        limit = 3 if self.insight_density == "high" else 2

        for t in relevant[:limit]:
            name = t.get("name", "this trend")
            mentions = t.get("mention_count", 0)
            shows = t.get("show_count", 0)
            keywords = t.get("keywords", [])

            if self.persuasion_framework == "urgency":
                point = (
                    f"At {show_name}, {name} was one of the dominant "
                    f"themes — we tracked {mentions} signals across "
                    f"{shows} events. The key areas driving this are "
                    f"{', '.join(keywords[:3])}. Companies that don't "
                    f"adapt their exhibit strategy risk falling behind. "
                    f"How is your team thinking about incorporating this?"
                )
            elif self.persuasion_framework == "opportunity":
                point = (
                    f"We're seeing a major opportunity around {name} at "
                    f"{show_name} — {mentions} signals across {shows} "
                    f"shows. Early movers in {', '.join(keywords[:3])} "
                    f"are capturing disproportionate attendee attention. "
                    f"What would it look like if your exhibit led on this?"
                )
            else:  # competitive
                point = (
                    f"Your competitors are already investing in {name} — "
                    f"we tracked {mentions} signals across {shows} events "
                    f"at {show_name}. The focus areas are "
                    f"{', '.join(keywords[:3])}. Where does your exhibit "
                    f"strategy stand relative to this shift?"
                )
            points.append(point)

        if not points:
            points.append(
                f"The trade show landscape in {industry} is shifting "
                f"rapidly. Based on our analysis of recent events, the "
                f"biggest opportunity is in experiential exhibit design. "
                f"What's your current approach?"
            )

        return points

    # ── Config interface ────────────────────────────────────────────────────

    def get_config(self) -> dict:
        """Return a snapshot of all modifiable parameters."""
        return {
            "brief_template": self.brief_template,
            "packet_template": self.packet_template,
            "max_trends_per_report": self.max_trends_per_report,
            "insight_density": self.insight_density,
            "persuasion_framework": self.persuasion_framework,
        }

    def update_config(self, **kwargs) -> None:
        """Update one or more modifiable parameters.

        Accepted keyword arguments: ``brief_template``, ``packet_template``,
        ``max_trends_per_report``, ``insight_density``,
        ``persuasion_framework``.
        """
        for key in (
            "brief_template",
            "packet_template",
            "max_trends_per_report",
            "insight_density",
            "persuasion_framework",
        ):
            if key in kwargs:
                setattr(self, key, kwargs[key])

    # ── Autoresearch loop ───────────────────────────────────────────────────

    def run_experiment(self) -> dict:
        """Modify a parameter, re-generate reports, evaluate, keep or discard.

        Each call:
          1. Snapshots current config and proxy quality metric.
          2. Perturbs one parameter (framework, density, or trend cap).
          3. Re-generates a sample report and measures quality proxy.
          4. Keeps the change only if the metric improved.

        Returns
        -------
        dict
            Experiment log entry.
        """
        old_config = self.get_config()
        old_metric = self._proxy_eval()

        # Choose what to perturb
        target = random.choice([
            "persuasion_framework",
            "insight_density",
            "max_trends_per_report",
        ])

        if target == "persuasion_framework":
            options = ["urgency", "opportunity", "competitive"]
            old_val = self.persuasion_framework
            options.remove(old_val)
            self.persuasion_framework = random.choice(options)
            change_desc = (
                f"persuasion_framework: {old_val} -> "
                f"{self.persuasion_framework}"
            )
        elif target == "insight_density":
            options = ["high", "medium", "low"]
            old_val = self.insight_density
            options.remove(old_val)
            self.insight_density = random.choice(options)
            change_desc = (
                f"insight_density: {old_val} -> {self.insight_density}"
            )
        else:
            old_val = self.max_trends_per_report
            self.max_trends_per_report = random.randint(3, 8)
            change_desc = (
                f"max_trends_per_report: {old_val} -> "
                f"{self.max_trends_per_report}"
            )

        new_metric = self._proxy_eval()

        kept = new_metric >= old_metric
        if not kept:
            self.brief_template = old_config["brief_template"]
            self.packet_template = old_config["packet_template"]
            self.max_trends_per_report = old_config["max_trends_per_report"]
            self.insight_density = old_config["insight_density"]
            self.persuasion_framework = old_config["persuasion_framework"]

        entry = {
            "timestamp": datetime.utcnow().isoformat(),
            "change": change_desc,
            "metric_before": round(old_metric, 4),
            "metric_after": round(new_metric, 4),
            "kept": kept,
        }
        self._experiment_log.append(entry)
        return entry

    # ── Internal helpers ────────────────────────────────────────────────────

    def _format_trend_section(self, trend: dict) -> str:
        """Format a single trend into a markdown section."""
        name = trend.get("name", "Unknown")
        rank = trend.get("rank", "?")
        score = trend.get("composite_score", 0)
        lifecycle = trend.get("lifecycle", "emerging")
        confidence = trend.get("confidence", 0)
        conf_pct = (
            int(confidence * 100) if confidence <= 1 else int(confidence)
        )
        description = trend.get("description", "")
        keywords = trend.get("keywords", [])

        lines = [
            f"## #{rank} {name} (Score: {score:.1f})",
            f"**Status:** {lifecycle.capitalize()} | "
            f"**Confidence:** {conf_pct}%",
            "",
            description,
        ]

        if self.insight_density == "high":
            if keywords:
                lines.append("")
                lines.append(
                    f"**Key signals:** {', '.join(keywords[:5])}"
                )
            prediction = trend.get("prediction", "")
            if prediction:
                lines.append("")
                lines.append(f"**Outlook:** {prediction}")
        elif self.insight_density == "medium":
            if keywords:
                lines.append("")
                lines.append(
                    f"**Key signals:** {', '.join(keywords[:3])}"
                )

        return "\n".join(lines)

    def _persuasion_callout(
        self, trend: dict, company_name: str
    ) -> str:
        """Generate a persuasion-framework-specific callout block."""
        name = trend.get("name", "this trend")
        lifecycle = trend.get("lifecycle", "emerging")

        if self.persuasion_framework == "urgency":
            if lifecycle == "growing":
                return (
                    f"> **Action Required:** This trend is accelerating. "
                    f"Companies that wait to incorporate {name} into their "
                    f"exhibit strategy risk falling behind competitors who "
                    f"are already adapting."
                )
            elif lifecycle == "emerging":
                return (
                    f"> **Early Mover Opportunity:** {name} is still "
                    f"emerging. First movers who build their exhibit "
                    f"narrative around this trend will establish category "
                    f"leadership."
                )
        elif self.persuasion_framework == "opportunity":
            return (
                f"> **Growth Opportunity:** {name} represents a whitespace "
                f"for {company_name} to differentiate. The trend is "
                f"{lifecycle} — positioning now captures outsized attention."
            )
        elif self.persuasion_framework == "competitive":
            return (
                f"> **Competitive Intelligence:** Leading companies in your "
                f"space are already investing in {name}. Aligning "
                f"{company_name}'s exhibit strategy with this trend is "
                f"essential to maintain competitive positioning."
            )
        return ""

    def _load_seed_trends(self) -> list[dict]:
        """Load seed trends for proxy evaluation."""
        path = DATA_DIR / "trends.json"
        if not path.exists():
            return []
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)

    def _proxy_eval(self) -> float:
        """Self-contained proxy quality metric for experiment evaluation.

        Generates a sample report from seed trends and measures:
          * content length (proxy for informativeness)
          * section count  (proxy for structure)
          * keyword density (proxy for specificity)
        """
        trends = self._load_seed_trends()
        if not trends:
            return 0.0

        # Generate a sample brief
        report = self.generate_trend_brief(trends)

        # Content length score (target: 1500-3000 chars)
        length = len(report)
        if length < 500:
            length_score = length / 500.0
        elif length <= 3000:
            length_score = 1.0
        else:
            length_score = max(0.5, 1.0 - (length - 3000) / 5000.0)

        # Section count (proxy for structure)
        sections = report.count("## ")
        section_score = min(1.0, sections / self.max_trends_per_report)

        # Keyword density (proxy for specificity)
        total_keywords = sum(
            len(t.get("keywords", [])) for t in trends[:self.max_trends_per_report]
        )
        keyword_mentions = sum(
            1 for t in trends[:self.max_trends_per_report]
            for kw in t.get("keywords", [])
            if kw.lower() in report.lower()
        )
        keyword_score = (
            keyword_mentions / max(total_keywords, 1)
        )

        return (
            0.35 * length_score
            + 0.35 * section_score
            + 0.30 * keyword_score
        )
