"""
ReportGenerator — The Output & Positioning Engine (Agent 3).

Turns raw intelligence from TrendAnalyzer into actionable output:
- Industry Trend Briefs (for sales reps)
- Prospect-Specific Intelligence Packets
- Design Trend Reports (for exhibit designers)
- Conversation Starters & Talking Points

Eval metric: report utility score — engagement, sharing, pipeline conversion.
"""

import copy
from typing import Optional


class ReportGenerator:
    """Generates actionable intelligence reports from trend data."""

    def __init__(self, config: Optional[dict] = None):
        self.config = config or self._default_config()

    @staticmethod
    def _default_config() -> dict:
        return {
            "brief_template": "industry_trend_brief",
            "packet_template": "prospect_intelligence",
            "max_trends_per_report": 5,
            "insight_density": "high",
            "persuasion_framework": "urgency",
        }

    def generate_trend_brief(self, trends: list[dict], industry: Optional[str] = None) -> str:
        """Generate an Industry Trend Brief — the 3-minute read for sales reps."""
        if industry:
            trends = [t for t in trends if industry in t.get("industries", [])]

        top = trends[: self.config["max_trends_per_report"]]
        title = f"Trade Show Trend Brief: {industry}" if industry else "Global Trade Show Trend Brief"

        lines = [f"# {title}", "", f"*{len(top)} key trends identified*", ""]

        for t in top:
            lifecycle = t.get("lifecycle", "emerging")
            score = t.get("composite_score", 0)
            confidence = t.get("confidence", 0)
            conf_pct = int(confidence * 100) if confidence <= 1 else int(confidence)

            lines.append(f"## #{t.get('rank', '?')} {t.get('name', 'Unknown')} (Score: {score:.1f})")
            lines.append(f"**Status:** {lifecycle.capitalize()} | **Confidence:** {conf_pct}%")
            lines.append("")
            lines.append(t.get("description", ""))
            lines.append("")

            keywords = t.get("keywords", [])
            if keywords:
                lines.append(f"**Key signals:** {', '.join(keywords[:5])}")
                lines.append("")

        lines.append("---")
        lines.append("*Generated by TradeShowTrendAgent*")
        return "\n".join(lines)

    def generate_prospect_packet(
        self, trends: list[dict], company_name: str, industry: str
    ) -> str:
        """Generate a Prospect-Specific Intelligence Packet."""
        relevant = [t for t in trends if industry in t.get("industries", [])]
        top = relevant[: self.config["max_trends_per_report"]]

        lines = [
            f"# Intelligence Packet: {company_name}",
            f"*Industry: {industry}*",
            "",
            "## Executive Summary",
            "",
            f"Based on analysis of {len(relevant)} trends relevant to {industry}, "
            f"here are the key insights for {company_name}'s trade show strategy:",
            "",
        ]

        for t in top:
            score = t.get("composite_score", 0)
            lines.append(f"### {t.get('name', 'Unknown')} ({score:.1f})")
            lines.append(t.get("description", ""))
            lines.append("")

            if self.config["persuasion_framework"] == "urgency":
                if t.get("lifecycle") == "growing":
                    lines.append(
                        f"> **Action Required:** This trend is accelerating. "
                        f"Companies that wait to incorporate {t.get('name', 'this')} "
                        f"into their exhibit strategy risk falling behind competitors "
                        f"who are already adapting."
                    )
                elif t.get("lifecycle") == "emerging":
                    lines.append(
                        f"> **Early Mover Opportunity:** {t.get('name', 'This trend')} "
                        f"is still emerging. First movers who build their exhibit "
                        f"narrative around this trend will establish category leadership."
                    )
            lines.append("")

        lines.extend([
            "## Recommended Next Steps",
            "",
            f"1. Audit current exhibit strategy against these {len(top)} trends",
            "2. Identify which trends align with your product roadmap",
            "3. Evaluate competitor exhibit strategies at upcoming shows",
            f"4. Develop a differentiated booth concept that positions {company_name} as a leader",
            "",
            "---",
            "*Generated by TradeShowTrendAgent*",
        ])
        return "\n".join(lines)

    def generate_design_report(self, trends: list[dict]) -> str:
        """Generate a Design Trend Report for exhibit designers."""
        top = trends[: self.config["max_trends_per_report"]]

        lines = [
            "# Exhibit Design Trend Report",
            "",
            "## Design Implications from Current Trade Show Trends",
            "",
        ]

        for t in top:
            lines.append(f"### {t.get('name', 'Unknown')}")
            lines.append(f"*{t.get('lifecycle', 'emerging').capitalize()} — Score: {t.get('composite_score', 0):.1f}*")
            lines.append("")

            implications = t.get("design_implications", "")
            if implications:
                lines.append(f"**Design Direction:** {implications}")
            else:
                lines.append(
                    f"**Design Direction:** Exhibits featuring {t.get('name', 'this trend')} "
                    f"should emphasize interactive demonstrations over static displays. "
                    f"Consider integrating live data feeds, hands-on stations, and "
                    f"workflow simulations that let attendees experience the technology."
                )
            lines.append("")

            keywords = t.get("keywords", [])
            if keywords:
                lines.append(f"**Design keywords:** {', '.join(keywords)}")
                lines.append("")

        lines.extend([
            "## General Design Trends",
            "",
            "- **Open engagement zones** outperforming guided-flow layouts",
            "- **Sustainable materials** driving 23% higher dwell time",
            "- **Interactive clinical/workflow simulations** replacing product showcases",
            "- **AI-powered personalization** for attendee experience",
            "- **Ambient technology** (LED-free lighting, spatial audio) replacing overt tech displays",
            "",
            "---",
            "*Generated by TradeShowTrendAgent*",
        ])
        return "\n".join(lines)

    def generate_talking_points(
        self, trends: list[dict], industry: str, show_name: str
    ) -> list[str]:
        """Generate conversation starters for sales reps."""
        relevant = [t for t in trends if industry in t.get("industries", [])]
        points = []

        for t in relevant[:3]:
            name = t.get("name", "this trend")
            score = t.get("composite_score", 0)
            mentions = t.get("mention_count", 0)
            shows = t.get("show_count", 0)
            keywords = t.get("keywords", [])

            points.append(
                f"At {show_name}, {name} was one of the dominant themes — "
                f"we tracked {mentions} signals across {shows} events. "
                f"The key areas driving this are {', '.join(keywords[:3])}. "
                f"How is your team thinking about incorporating this into your "
                f"exhibit strategy?"
            )

        if not points:
            points.append(
                f"The trade show landscape in {industry} is shifting rapidly. "
                f"Based on our analysis of recent events, the biggest opportunity "
                f"is in experiential exhibit design. What's your current approach?"
            )

        return points

    def get_config(self) -> dict:
        return copy.deepcopy(self.config)

    def update_config(self, **kwargs) -> None:
        for key, value in kwargs.items():
            if key in self.config:
                self.config[key] = value

    def run_experiment(self) -> dict:
        """Test different report configurations and measure quality."""
        # Placeholder for report quality A/B testing
        return {
            "template": self.config["brief_template"],
            "density": self.config["insight_density"],
            "framework": self.config["persuasion_framework"],
            "status": "baseline_established",
        }
